import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

type Data = {
  id: string;
  title: string;
  description: string;
  image: string;
};
type City = {
  id: string;
  title: string;
  description: string;
  image: string;
};

export default function Home({ data }: Data) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About Us</a>
        </nav>
      </header>
      <main className="">
        <div>
          {data.map((city: City) => {
            return (
              <a key={city.id} href={`/events/${city.id}`}>
                <Image
                  width={100}
                  height={100}
                  src={city.image}
                  alt={city.title}
                />
                <h2 className="text-2xl">Events in {city.id}</h2>
                <p>{city.description}</p>
              </a>
            );
          })}
        </div>
      </main>
      <footer className=""></footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../../data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
